import '../models/mechanic.dart';
import '../models/spare_part.dart';

class MockData {
  MockData._();

  static const List<Mechanic> mechanics = [
    Mechanic(
      id: 'mec-001',
      name: 'Joseph Okello',
      businessName: 'Okello Auto Repairs',
      specialty: 'Engine & Transmission',
      services: ['Engine repair', 'Transmission service', 'Diagnostics', 'Clutch replacement'],
      rating: 4.8,
      reviewCount: 128,
      available: true,
      phone: '+256 772 111 001',
      address: 'Plot 12, Ntinda Road, Ntinda',
      latitude: 0.3553,
      longitude: 32.6010,
      experience: '12 years',
    ),
    Mechanic(
      id: 'mec-002',
      name: 'Grace Namugera',
      businessName: 'Namugera Tyres & Battery Centre',
      specialty: 'Tyres & Batteries',
      services: ['Tyre replacement', 'Battery boost', 'Battery replacement', 'Wheel alignment'],
      rating: 4.6,
      reviewCount: 74,
      available: true,
      phone: '+256 782 220 002',
      address: 'Bukoto Street, Bukoto',
      latitude: 0.3411,
      longitude: 32.5947,
      experience: '8 years',
    ),
    Mechanic(
      id: 'mec-003',
      name: 'David Ssemakula',
      businessName: 'Bwaise Vehicle Clinic',
      specialty: 'General Repairs',
      services: ['General service', 'Oil change', 'Brake service', 'Towing'],
      rating: 4.4,
      reviewCount: 52,
      available: true,
      phone: '+256 700 333 003',
      address: 'Kampala – Hoima Road, Bwaise',
      latitude: 0.3550,
      longitude: 32.5680,
      experience: '10 years',
    ),
    Mechanic(
      id: 'mec-004',
      name: 'Ivan Kato',
      businessName: 'Wandegeya Auto Electricians',
      specialty: 'Auto Electrical',
      services: ['Starter motors', 'Alternators', 'Wiring', 'Battery diagnostics'],
      rating: 4.7,
      reviewCount: 41,
      available: false,
      phone: '+256 774 444 004',
      address: 'Makerere Hill Road, Wandegeya',
      latitude: 0.3330,
      longitude: 32.5744,
      experience: '9 years',
    ),
    Mechanic(
      id: 'mec-005',
      name: 'Robert Mukasa',
      businessName: 'Nakawa Diesel Specialists',
      specialty: 'Diesel Engines',
      services: ['Diesel injector service', 'Turbo repair', 'Engine overhaul', 'Fuel pump repair'],
      rating: 4.5,
      reviewCount: 60,
      available: true,
      phone: '+256 788 555 005',
      address: 'Nakawa Market Road, Nakawa',
      latitude: 0.3269,
      longitude: 32.6119,
      experience: '15 years',
    ),
    Mechanic(
      id: 'mec-006',
      name: 'Faridah Nabirye',
      businessName: 'Entebbe Road Body & Paint',
      specialty: 'Body Work & Paint',
      services: ['Panel beating', 'Spray painting', 'Denting', 'Underbody protection'],
      rating: 4.3,
      reviewCount: 33,
      available: true,
      phone: '+256 701 666 006',
      address: 'Entebbe Road, Ndeeba',
      latitude: 0.2990,
      longitude: 32.6170,
      experience: '7 years',
    ),
    Mechanic(
      id: 'mec-007',
      name: 'Moses Lubega',
      businessName: 'Lubaga Brake & Suspension',
      specialty: 'Brakes & Suspension',
      services: ['Brake pad replacement', 'Disc machining', 'Shock absorbers', 'Tie rods'],
      rating: 4.9,
      reviewCount: 90,
      available: true,
      phone: '+256 755 777 007',
      address: 'Lubaga Road, Lubaga',
      latitude: 0.3022,
      longitude: 32.5617,
      experience: '11 years',
    ),
    Mechanic(
      id: 'mec-008',
      name: 'Brian Wasswa',
      businessName: 'Mengo Mobile Mechanic Express',
      specialty: 'Mobile 24/7',
      services: ['Mobile repairs', 'Jump start', 'Fuel delivery', 'Tyre change', 'Emergency calls'],
      rating: 4.6,
      reviewCount: 88,
      available: true,
      phone: '+256 777 888 008',
      address: 'Circular Road, Mengo',
      latitude: 0.3032,
      longitude: 32.5630,
      experience: '6 years',
    ),
  ];

  static const List<SparePart> spareParts = [
    SparePart(
      id: 'prt-001',
      name: '12V Car Battery (60Ah)',
      category: 'Batteries',
      price: 450000,
      supplier: 'AutoMart Uganda',
      supplierArea: 'Kampala Road',
      inStock: true,
      vehicleCompat: 'Most saloon cars & SUVs',
    ),
    SparePart(
      id: 'prt-002',
      name: 'Disc Brake Pads – Front',
      category: 'Brakes',
      price: 85000,
      supplier: 'Lugogo Spares',
      supplierArea: 'Lugogo',
      inStock: true,
      vehicleCompat: 'Toyota, Nissan, Honda',
    ),
    SparePart(
      id: 'prt-003',
      name: 'Engine Oil 5W-30 (4 Litres)',
      category: 'Lubricants',
      price: 95000,
      supplier: 'Nakawa Auto Spares',
      supplierArea: 'Nakivubo',
      inStock: true,
      vehicleCompat: 'Petrol & diesel engines',
    ),
    SparePart(
      id: 'prt-004',
      name: 'Spark Plug (set of 4)',
      category: 'Ignition',
      price: 28000,
      supplier: 'City Auto Spares',
      supplierArea: 'Bombo Road',
      inStock: true,
      vehicleCompat: 'Petrol engines',
    ),
    SparePart(
      id: 'prt-005',
      name: 'Engine Air Filter',
      category: 'Filters',
      price: 22000,
      supplier: 'City Auto Spares',
      supplierArea: 'Bombo Road',
      inStock: true,
      vehicleCompat: 'Universal fit',
    ),
    SparePart(
      id: 'prt-006',
      name: 'Clutch Disc & Pressure Plate Kit',
      category: 'Transmission',
      price: 380000,
      supplier: 'Lugogo Spares',
      supplierArea: 'Lugogo',
      inStock: false,
      vehicleCompat: 'Toyota Corolla, Mitsubishi',
    ),
    SparePart(
      id: 'prt-007',
      name: 'Tyre 205/55 R16',
      category: 'Tyres',
      price: 340000,
      supplier: 'Kampala Tyre Depot',
      supplierArea: 'Kira Road',
      inStock: true,
      vehicleCompat: 'Sedans & compact SUVs',
    ),
    SparePart(
      id: 'prt-008',
      name: 'Alternator (12V)',
      category: 'Electrical',
      price: 520000,
      supplier: 'Nakawa Auto Spares',
      supplierArea: 'Nakivubo',
      inStock: true,
      vehicleCompat: 'Toyota, Daihatsu',
    ),
    SparePart(
      id: 'prt-009',
      name: 'Radiator Coolant (5 Litres)',
      category: 'Cooling',
      price: 45000,
      supplier: 'AutoMart Uganda',
      supplierArea: 'Kampala Road',
      inStock: true,
      vehicleCompat: 'All vehicle types',
    ),
    SparePart(
      id: 'prt-010',
      name: 'Electric Fuel Pump',
      category: 'Fuel System',
      price: 290000,
      supplier: 'City Auto Spares',
      supplierArea: 'Bombo Road',
      inStock: true,
      vehicleCompat: 'Fuel injection systems',
    ),
    SparePart(
      id: 'prt-011',
      name: 'Rear Shock Absorber',
      category: 'Suspension',
      price: 165000,
      supplier: 'Lugogo Spares',
      supplierArea: 'Lugogo',
      inStock: true,
      vehicleCompat: 'Toyota Corolla',
    ),
    SparePart(
      id: 'prt-012',
      name: 'LED Headlight Bulb (H4)',
      category: 'Lighting',
      price: 18000,
      supplier: 'Kampala Tyre Depot',
      supplierArea: 'Kira Road',
      inStock: true,
      vehicleCompat: 'Universal fit',
    ),
  ];

  static const List<String> issueTypes = [
    'Battery / won\'t start',
    'Flat or punctured tyre',
    'Engine overheating',
    'Engine noise / warning light',
    'Brake problem',
    'Fuel delivery / no fuel',
    'Transmission / gearbox problem',
    'Accident / collision',
    'Locked out of vehicle',
    'Other mechanical problem',
  ];

  static const List<String> vehicleTypes = [
    'Saloon',
    'SUV',
    'Pickup',
    'Van',
    'Truck',
    'Bus',
    'Motorcycle',
  ];

  static const List<String> fuelTypes = ['Petrol', 'Diesel', 'Electric', 'Hybrid'];
}